First version of the Insomnia section
tecladocode/rest-apis-flask-python pull request #101
Opened 2022-12-06 23:58 UTC by LukaMilivojevic

2022-12-07 10:23 UTC, jslvtr requested changes

2022-12-07 10:56 UTC, LukaMilivojevic commented on docs/docs/08_flask_jwt_extended/11_insomnia_request_chaining/README.md
> +Inside of this window, there is a `Filter` field. In this field, we are telling Insomnia which part of the response we want to get from it. The prompt is started with the dollar sign `$` and then we
Added it 👍

2022-12-07 11:13 UTC, LukaMilivojevic commented on docs/docs/08_flask_jwt_extended/11_insomnia_request_chaining/README.md
> +Add a new environment variable called `access_token`, and for its value you should follow the same process from above. Make sure to wrap the `Response -> Body Attribute` with quotation marks, as show
Added a short reminder

2022-12-09 11:25 UTC, jslvtr approved these changes

2022-12-09 11:25 UTC, merged